name: Bun
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  push:
    name: "esdock:bun"
    runs-on: docker
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - uses: redhat-actions/buildah-build@v2
        with:
          image: esdock
          tags: bun
          registry: ghcr.io/zastinian
          containerfiles: ./bun/Dockerfile
          context: ./bun
          platforms: linux/amd64,linux/arm64
          oci: true
