name: Chrome NodeJS

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: docker
    strategy:
      fail-fast: false
      matrix:
        tag: [12, 14, 16, 18, 20, 22, 24]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/zastinian/esdock:chrnodejs_${{ matrix.tag }}
          context: ./chrnodejs
          file: ./chrnodejs/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
