name: Chrome NodeJS
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  push:
    name: "esdock:chrnodejs_${{ matrix.tag }}"
    runs-on: docker
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 12
          - 14
          - 16
          - 18
          - 20
          - 22
          - 24
    steps:
      - uses: actions/checkout@v4
      
      - uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - uses: redhat-actions/buildah-build@v2
        with:
          image: esdock
          tags: chrnodejs_${{ matrix.tag }}
          registry: ghcr.io/zastinian
          containerfiles: ./chrnodejs/${{ matrix.tag }}/Dockerfile
          context: ./chrnodejs
          platforms: linux/amd64
          oci: true
