name: Java
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  push:
    name: "esdock:java_${{ matrix.tag }}"
    runs-on: docker
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 8
          - 11
          - 17
          - 21
          - 25
    steps:
      - uses: https://github.com/actions/checkout@v4
      - uses: https://github.com/redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: https://github.com/redhat-actions/buildah-build@v2
        with:
          image: esdock
          tags: java_${{ matrix.tag }}
          registry: ghcr.io/zastinian
          containerfiles: ./java/${{ matrix.tag }}/Dockerfile
          context: ./java
          platforms: linux/amd64,linux/arm64
          oci: true
