name: NodeJS
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  push:
    name: "esdock:nodejs_${{ matrix.tag }}"
    runs-on: docker
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 12
          - 14
          - 16
          - 18
          - 20
          - 22
          - 24
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./nodejs
          file: ./nodejs/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/zastinian/esdock:nodejs_${{ matrix.tag }}
