when:
  - event: push
    branch: master
    path: { include: [ "bun/*" ] }

steps:
  - name: publish-bun
    image: woodpeckerci/plugin-docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/${CI_REPO_OWNER}/esdock
      username: ${CI_REPO_OWNER}
      password:
        from_secret: REGISTRY_TOKEN
      context: bun
      dockerfile: bun/Dockerfile
      tags: bun
      platforms: linux/amd64,linux/arm64