matrix:
  TAG_VERSION:
    - 12
    - 14
    - 16
    - 18
    - 20
    - 22

when:
  - event: push
    branch: master

steps:
  build-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/zastinian/esdock
      tags: chrnodejs_${TAG_VERSION}
      dockerfile: chrnodejs/${TAG_VERSION}/Dockerfile
      context: chrnodejs
      platforms: linux/amd64
      username: zastinian
      password:
        from_secret: REGISTRY_TOKEN
