when:
  - event: push
    branch: master

steps:
  build-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/zastinian/esdock
      tags: html
      dockerfile: html/Dockerfile
      context: html
      platforms: linux/amd64,linux/arm64
      username: zastinian
      password:
        from_secret: REGISTRY_TOKEN
