when:
  - event: push
    branch: master
    path: { include: [ "html/*" ] }

steps:
  - name: publish-html
    image: woodpeckerci/plugin-docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/${CI_REPO_OWNER}/esdock
      username: ${CI_REPO_OWNER}
      password:
        from_secret: REGISTRY_TOKEN
      context: html
      dockerfile: html/Dockerfile
      tags: html
      platforms: linux/amd64,linux/arm64