matrix:
  TAG_VERSION:
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22

when:
  - event: push
    branch: master

steps:
  build-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/${CI_REPO_OWNER}/esdock
      tags: java_${TAG_VERSION}
      dockerfile: java/${TAG_VERSION}/Dockerfile
      context: java
      platforms: linux/amd64,linux/arm64
      username: ${CI_REPO_OWNER}
      password:
        from_secret: registry_token
