matrix:
  TAG: [16, 17, 18, 19, 20, 21, 22]

when:
  - event: push
    branch: master
    path: { include: [ "java/**" ] }

steps:
  publish-java:
    image: woodpeckerci/plugin-docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/${CI_REPO_OWNER}/esdock
      username: ${CI_REPO_OWNER}
      password:
        from_secret: REGISTRY_TOKEN
      context: java
      dockerfile: java/${TAG}/Dockerfile
      tags: java_${TAG}
      platforms: linux/amd64,linux/arm64
