matrix:
  TAG: [12, 14, 16, 18, 20, 22]

when:
  - event: push
    branch: master
    path: { include: [ "nodejs/**" ] }

steps:
  publish-nodejs:
    image: woodpeckerci/plugin-docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/${CI_REPO_OWNER}/esdock
      username: ${CI_REPO_OWNER}
      password:
        from_secret: REGISTRY_TOKEN
      context: nodejs
      dockerfile: nodejs/${TAG}/Dockerfile
      tags: nodejs_${TAG}
      platforms: linux/amd64,linux/arm64
