matrix:
  TAG_VERSION:
    - 12
    - 14
    - 16
    - 18
    - 20
    - 22
    - 24

when:
  - event: push
    branch: master

steps:
  build-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/zastinian/esdock
      tags: nodejs_${TAG_VERSION}
      dockerfile: nodejs/${TAG_VERSION}/Dockerfile
      context: nodejs
      platforms: linux/amd64,linux/arm64
      username: zastinian
      password:
        from_secret: REGISTRY_TOKEN
